var annotated_dup =
[
    [ "EntryGateController", "classEntryGateController.html", "classEntryGateController" ],
    [ "Esp32Gpio", "classEsp32Gpio.html", "classEsp32Gpio" ],
    [ "EspGpioInput", "classEspGpioInput.html", "classEspGpioInput" ],
    [ "EspGpioOutput", "classEspGpioOutput.html", "classEspGpioOutput" ],
    [ "EspServoOutput", "classEspServoOutput.html", "classEspServoOutput" ],
    [ "Event", "structEvent.html", "structEvent" ],
    [ "EventDrivenStateMachine", "classEventDrivenStateMachine.html", "classEventDrivenStateMachine" ],
    [ "EventLogger", "classEventLogger.html", "classEventLogger" ],
    [ "EventRecorder", "classEventRecorder.html", "classEventRecorder" ],
    [ "ExitGateController", "classExitGateController.html", "classExitGateController" ],
    [ "FreeRtosEventBus", "classFreeRtosEventBus.html", "classFreeRtosEventBus" ],
    [ "Gate", "classGate.html", "classGate" ],
    [ "GateController", "classGateController.html", "classGateController" ],
    [ "IEventBus", "classIEventBus.html", "classIEventBus" ],
    [ "IGate", "classIGate.html", "classIGate" ],
    [ "IGpioInput", "classIGpioInput.html", "classIGpioInput" ],
    [ "IGpioOutput", "classIGpioOutput.html", "classIGpioOutput" ],
    [ "InputEvent", "structInputEvent.html", "structInputEvent" ],
    [ "ITicketService", "classITicketService.html", "classITicketService" ],
    [ "MockGpio", "classMockGpio.html", "classMockGpio" ],
    [ "MockMotorController", "classMockMotorController.html", "classMockMotorController" ],
    [ "MotorConfig", "structMotorConfig.html", "structMotorConfig" ],
    [ "MotorController", "classMotorController.html", "classMotorController" ],
    [ "MotorSpeed", "structMotorSpeed.html", "structMotorSpeed" ],
    [ "OutputEvent", "structOutputEvent.html", "structOutputEvent" ],
    [ "ParkingGarageConfig", "classParkingGarageConfig.html", "classParkingGarageConfig" ],
    [ "ParkingGarageSystem", "classParkingGarageSystem.html", "classParkingGarageSystem" ],
    [ "Ticket", "structTicket.html", "structTicket" ],
    [ "TicketService", "classTicketService.html", "classTicketService" ]
];